test-symfony
restarteco/backend-ci pull request #2
Opened 2022-03-23 10:58 UTC by rush93

2022-03-23 13:53 UTC, Chnapy requested changes

2022-03-23 13:53 UTC, Chnapy commented on symfony-test-ci/action.yaml
> +  color: red
useless

2022-03-23 13:53 UTC, Chnapy commented on symfony-test-ci/action.yaml
> +      uses: actions/checkout@v2
```suggestion
      uses: actions/checkout@v3
```

2022-03-23 13:53 UTC, Chnapy commented on symfony-test-ci/action.yaml
> +      shell: bash
useless

2022-03-23 13:53 UTC, Chnapy commented on symfony-test-ci/action.yaml
> +        node-version: '14'
```suggestion
        node-version: '12.22.6'
```

2022-03-23 15:15 UTC, rush93 commented on symfony-test-ci/action.yaml
> +  color: red
usefull

2022-03-24 10:25 UTC, TimotheeOng1910 approved these changes

2022-03-24 13:43 UTC, merged